version: "3.7"

services:
    ca-vis:
        container_name: ca-vis
        stdin_open: true    # -i
        tty: true   # -t
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
