version: "3.7"

services:
    frontend:
        container_name: frontend
        stdin_open: true # -i (equivalent from docker command options)
        tty: true # -t (equivalent from docker command options)
        build:
            context: .
            dockerfile: Dockerfile-frontend
        volumes:
            - ".:/app"
            - "/app/node_modules"
        ports:
            - 3001:3000
        environment:
            - CHOKIDAR_USEPOLLING=true

    backend:
        container_name: backend
        stdin_open: true # -i (equivalent from docker command options)
        tty: true # -t (equivalent from docker command options)
        build:
            context: .
            dockerfile: Dockerfile-backend
        #volumes:
        #    - '.:/app'
        #    - '/app/node_modules'
        ports:
            - 5001:5000
        environment:
            - CHOKIDAR_USEPOLLING=true
